<?php

const PROVIDER_MANDRILL = 1;
const PROVIDER_POSTMARK = 2;
const PROVIDER_TWILIO = 3;
const PROVIDER_FIREBASE = 4;
const PROVIDER_WS = 5;

const MAIL_PROVIDERS = [
    PROVIDER_MANDRILL,
    PROVIDER_POSTMARK
];

const SMS_PROVIDERS = [
    PROVIDER_TWILIO
];

const PUSH_PROVIDERS = [
    PROVIDER_FIREBASE
];

const WS_PROVIDERS = [
    PROVIDER_WS
];
